// Keep the experimental shell's copy together for the localization pass.
export const sidebarCopy = {
  home: "Hem",
  library: "Bibliotek",
  courses: "Kurser",
  workspace: "Arbetsyta",
  canvas: "Plats för nästa kapitel.",
  views: {
    dashboard: "Hem",
    inbox: "Inkorg",
    "super-actions": "Superåtgärder",
    settings: "Inställningar",
    cards: "Anki-kort",
    workspace: "Bibliotek",
  },
  minimize: "Minimera",
  maximize: "Maximera eller återställ",
  close: "Stäng",
  collapse: "Dölj sidofält",
  expand: "Visa sidofält",
  search: "Sök i biblioteket",
  clearSearch: "Avsluta sökning",
  newCourse: "Skapa kurs",
  newModule: "Ny modul",
  newLecture: "Ny föreläsning",
  newTopic: "Nytt ämne",
  rename: "Byt namn",
  name: "Namn",
  save: "Spara",
  cancel: "Avbryt",
  help: "Hjälp och kortkommandon",
  empty: "Ditt bibliotek börjar här.",
  emptyAction: "Skapa din första kurs",
  noResults: "Inga träffar",
  menu: "Alternativ för",
  open: "Öppna",
  shortcuts: "Kortkommandon",
  feedback: "Exportera diagnostik",
  dismiss: "Stäng meddelande",
  moveFailed: "Objektet kunde inte flyttas.",
  diagnosticDone: "Diagnostik exporterad.",
  type: {
    workspace: "Bibliotek",
    course: "Kurs",
    module: "Modul",
    lecture: "Föreläsning",
    topic: "Ämne",
  },
};
