export const lectureCopy = {
  slides: "Slides",
  transcript: "Transkript",
  notes: "Anteckningar",
  markers: "Markeringar",
  importPdf: "Lägg till PDF",
  replacePdf: "Byt PDF",
  importAudio: "Importera ljud",
  pdfEmpty: "Börja med dina slides",
  pdfHint: "Släpp en PDF här eller välj en fil.",
  audioEmpty: "Ljud när du behöver det",
  audioHint: "Spela in föreläsningen eller lägg till en ljudfil.",
  record: "Spela in",
  stop: "Stoppa och spara",
  recording: "Spelar in",
  paused: "Pausad",
  transcribe: "Transkribera",
  transcriptEmpty: "Från tal till sökbar text",
  transcriptHint:
    "Lägg till ljud och transkribera med ditt sparade val i inställningarna.",
  search: "Sök i transkriptet",
  noResults: "Ingen matchande text.",
  more: "Visa fler avsnitt",
  notesPlaceholder: "Dina tankar, frågor och sådant du vill komma ihåg…",
  saved: "Sparat lokalt",
  savePending: "Sparar…",
  addMarker: "Markera ögonblick",
  markersEmpty: "Ett ögonblick att återvända till",
  markerHint:
    "Markera något viktigt i ljudet och lägg till en kort anteckning.",
  cards: "Anki-kort",
  cardsEmpty: "Inga kort i den här föreläsningen ännu.",
  cardsHint: "Här kan du granska och godkänna föreläsningens befintliga kort.",
  approve: "Godkänn",
  approved: "Godkänt",
  synced: "Synkat",
  approveAll: "Godkänn alla",
  close: "Stäng",
  retry: "Försök igen",
  loadingPdf: "Öppnar PDF…",
  pdfError: "PDF:en kunde inte öppnas. Försök igen eller välj en annan fil.",
  previous: "Föregående sida",
  next: "Nästa sida",
  fit: "Anpassa till bredd",
  zoomIn: "Zooma in",
  zoomOut: "Zooma ut",
  play: "Spela",
  pause: "Pausa",
  back: "Bakåt 10 sekunder",
  forward: "Framåt 10 sekunder",
  speed: "Uppspelningshastighet",
  mute: "Stäng av ljud",
  unmute: "Slå på ljud",
  timeline: "Ljudposition",
  pending: "En tidigare inspelning kan återställas.",
  recover: "Återställ inspelning",
  micError:
    "Mikrofonen kunde inte startas. Kontrollera mikrofonbehörigheten och försök igen.",
  audioError: "Ljudet kunde inte spelas upp. Prova en annan ljudfil.",
  loading: "Läser fil…",
  importFailed: "Filen kunde inte importeras.",
  queued: "Transkriberingen har lagts i kön.",
  alreadyTranscribed:
    "Transkript finns redan. Transkribera igen? Det nuvarande transkriptet ersätts när den nya transkriberingen lyckas.",
  cancel: "Avbryt",
  replaceTranscript: "Transkribera igen",
  removeMarker: "Ta bort markering",
} as const;

export function formatTime(value: number) {
  const seconds = Math.max(0, Math.floor(Number.isFinite(value) ? value : 0));
  return seconds >= 3600
    ? `${Math.floor(seconds / 3600)}:${String(Math.floor(seconds / 60) % 60).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`
    : `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, "0")}`;
}
