import type { ThemePalette } from "./types";

export const builtInPalettes: ThemePalette[] = [
  {
  id: "chalk-neutral",
  name: "Kalk",
  background: "#ffffff",
  surface: "#ffffff",
  surfaceMuted: "#f4f4f5",
  surfaceHover: "#e4e4e7",
  text: "#18181b",
  textMuted: "#71717a",
  textSubtle: "#a1a1aa",
  border: "#e4e4e7",
  borderStrong: "#d4d4d8",
  primary: "#18181b",
  primaryHover: "#27272a",
  primarySoft: "#f4f4f5",
  primarySoftHover: "#e4e4e7",
  primaryText: "#fafafa",
  accentText: "#27272a",
  focusRing: "#a1a1aa",
  hero: "#18181b",
  heroText: "#fafafa",
},
{
  id: "graphite",
  name: "Grafit",
  background: "#09090b",
  surface: "#18181b",
  surfaceMuted: "#27272a",
  surfaceHover: "#3f3f46",
  text: "#fafafa",
  textMuted: "#a1a1aa",
  textSubtle: "#71717a",
  border: "#27272a",
  borderStrong: "#3f3f46",
  primary: "#fafafa",
  primaryHover: "#e4e4e7",
  primarySoft: "#27272a",
  primarySoftHover: "#3f3f46",
  primaryText: "#18181b",
  accentText: "#d4d4d8",
  focusRing: "#71717a",
  hero: "#000000",
  heroText: "#fafafa",
},
  {
    id: "chalk",
    name: "Krita",
    background: "#f7f8fa",
    surface: "#ffffff",
    surfaceMuted: "#f1f5f9",
    surfaceHover: "#e9eef5",
    text: "#0f172a",
    textMuted: "#64748b",
    textSubtle: "#94a3b8",
    border: "#e2e8f0",
    borderStrong: "#cbd5e1",
    primary: "#7c3aed",
    primaryHover: "#6d28d9",
    primarySoft: "#ede9fe",
    primarySoftHover: "#ddd6fe",
    primaryText: "#ffffff",
    accentText: "#5b21b6",
    focusRing: "#c4b5fd",
    hero: "#0f172a",
    heroText: "#ffffff",
  },
  {
    id: "fjord",
    name: "Fjord",
    background: "#f1f7f9",
    surface: "#fbfdfe",
    surfaceMuted: "#deedf2",
    surfaceHover: "#e7f1f4",
    text: "#102a35",
    textMuted: "#58727d",
    textSubtle: "#829ba5",
    border: "#c8dce3",
    borderStrong: "#a9c6cf",
    primary: "#087e8b",
    primaryHover: "#066874",
    primarySoft: "#cdeff1",
    primarySoftHover: "#b5e3e7",
    primaryText: "#ffffff",
    accentText: "#055d67",
    focusRing: "#7fd1d7",
    hero: "#123b4a",
    heroText: "#ffffff",
  },
  {
    id: "paper",
    name: "Papper",
    background: "#f6f1e8",
    surface: "#fffaf0",
    surfaceMuted: "#eee6d8",
    surfaceHover: "#e8ddcc",
    text: "#312b24",
    textMuted: "#756b60",
    textSubtle: "#9a8c7d",
    border: "#ddd2c1",
    borderStrong: "#c7b9a4",
    primary: "#a34a28",
    primaryHover: "#873b20",
    primarySoft: "#f5d8c8",
    primarySoftHover: "#edc3ad",
    primaryText: "#ffffff",
    accentText: "#7c351e",
    focusRing: "#dca486",
    hero: "#3c2b1f",
    heroText: "#fffaf0",
  },
  {
    id: "midnight",
    name: "Midnatt",
    background: "#0b1020",
    surface: "#151d31",
    surfaceMuted: "#1d2941",
    surfaceHover: "#23304a",
    text: "#eef2ff",
    textMuted: "#9ba9c6",
    textSubtle: "#7484a5",
    border: "#2d3a55",
    borderStrong: "#40506f",
    primary: "#8b7cf6",
    primaryHover: "#a79cff",
    primarySoft: "#302b63",
    primarySoftHover: "#3b3578",
    primaryText: "#ffffff",
    accentText: "#c8c2ff",
    focusRing: "#7468df",
    hero: "#070b16",
    heroText: "#eef2ff",
  },
  {
    id: "forest",
    name: "Skog",
    background: "#0d1713",
    surface: "#17231e",
    surfaceMuted: "#203229",
    surfaceHover: "#24382e",
    text: "#edf7f1",
    textMuted: "#9ab5a6",
    textSubtle: "#6f8f7c",
    border: "#30483b",
    borderStrong: "#446151",
    primary: "#4fbd83",
    primaryHover: "#68d69a",
    primarySoft: "#214c36",
    primarySoftHover: "#2b6144",
    primaryText: "#07130d",
    accentText: "#a1ebbd",
    focusRing: "#46a873",
    hero: "#07110d",
    heroText: "#edf7f1",
  },
  {
    id: "plum",
    name: "Plommon",
    background: "#1b111c",
    surface: "#29192a",
    surfaceMuted: "#39213a",
    surfaceHover: "#442944",
    text: "#f8edf7",
    textMuted: "#c0a2bd",
    textSubtle: "#967493",
    border: "#50304f",
    borderStrong: "#684166",
    primary: "#dc72c2",
    primaryHover: "#ee91d6",
    primarySoft: "#57234d",
    primarySoftHover: "#6b2d5f",
    primaryText: "#25101f",
    accentText: "#ffc6ef",
    focusRing: "#c55bad",
    hero: "#160c17",
    heroText: "#f8edf7",
  },
  {
  id: "catppuccin-latte",
  name: "Latte",
  background: "#eff1f5",
  surface: "#ffffff",
  surfaceMuted: "#e6e9ef",
  surfaceHover: "#dce0e8",
  text: "#4c4f69",
  textMuted: "#6c6f85",
  textSubtle: "#9ca0b0",
  border: "#ccd0da",
  borderStrong: "#bcc0cc",
  primary: "#8839ef",
  primaryHover: "#7832d2",
  primarySoft: "#e0d5f4",
  primarySoftHover: "#d0baf3",
  primaryText: "#ffffff",
  accentText: "#58259b",
  focusRing: "#ac74f4",
  hero: "#4c4f69",
  heroText: "#ffffff",
},
{
  id: "catppuccin-frappe",
  name: "Frappé",
  background: "#232634",
  surface: "#292c3c",
  surfaceMuted: "#303446",
  surfaceHover: "#414559",
  text: "#c6d0f5",
  textMuted: "#a5adce",
  textSubtle: "#737994",
  border: "#51576d",
  borderStrong: "#626880",
  primary: "#ca9ee6",
  primaryHover: "#d2adea",
  primarySoft: "#4f4966",
  primarySoftHover: "#66597e",
  primaryText: "#232634",
  accentText: "#cfa8e9",
  focusRing: "#d7b6ec",
  hero: "#191b24",
  heroText: "#c6d0f5",
},
{
  id: "catppuccin-macchiato",
  name: "Macchiato",
  background: "#181926",
  surface: "#1e2030",
  surfaceMuted: "#24273a",
  surfaceHover: "#363a4f",
  text: "#cad3f5",
  textMuted: "#a5adcb",
  textSubtle: "#6e738d",
  border: "#494d64",
  borderStrong: "#5b6078",
  primary: "#c6a0f6",
  primaryHover: "#cfaef7",
  primarySoft: "#443f60",
  primarySoftHover: "#5d517c",
  primaryText: "#181926",
  accentText: "#ccaaf7",
  focusRing: "#d4b8f8",
  hero: "#11121b",
  heroText: "#cad3f5",
},
{
  id: "catppuccin-mocha",
  name: "Mocha",
  background: "#11111b",
  surface: "#181825",
  surfaceMuted: "#1e1e2e",
  surfaceHover: "#313244",
  text: "#cdd6f4",
  textMuted: "#a6adc8",
  textSubtle: "#6c7086",
  border: "#45475a",
  borderStrong: "#585b70",
  primary: "#cba6f7",
  primaryHover: "#d3b3f8",
  primarySoft: "#413956",
  primarySoftHover: "#5b4e74",
  primaryText: "#11111b",
  accentText: "#d0aff8",
  focusRing: "#d8bcf9",
  hero: "#0c0c13",
  heroText: "#cdd6f4",
},
{
  id: "anthropic-claude-light",
  name: "Claude Light",
  background: "#f5f4ed",
  surface: "#ffffff",
  surfaceMuted: "#f0eee5",
  surfaceHover: "#e8e5d9",
  text: "#141413",
  textMuted: "#5a564d",
  textSubtle: "#8a8577",
  border: "#e3e0d3",
  borderStrong: "#d3cfbf",
  primary: "#c96442",
  primaryHover: "#b0532f",
  primarySoft: "#f3ded2",
  primarySoftHover: "#ecc9b5",
  primaryText: "#ffffff",
  accentText: "#8a4022",
  focusRing: "#3898ec",
  hero: "#141413",
  heroText: "#f5f4ed",
},
{
  id: "anthropic-claude-dark",
  name: "Claude Dark",
  background: "#141413",
  surface: "#2b2a27",
  surfaceMuted: "#34322e",
  surfaceHover: "#3d3a35",
  text: "#f5f4ed",
  textMuted: "#a39e93",
  textSubtle: "#7d786c",
  border: "#3d3a35",
  borderStrong: "#4e4a43",
  primary: "#d97757",
  primaryHover: "#e2896c",
  primarySoft: "#45332a",
  primarySoftHover: "#56402f",
  primaryText: "#141413",
  accentText: "#e2916f",
  focusRing: "#3898ec",
  hero: "#000000",
  heroText: "#f5f4ed",
},
{
  id: "openai-chatgpt-light",
  name: "ChatGPT Light",
  background: "#ffffff",
  surface: "#ffffff",
  surfaceMuted: "#f7f7f8",
  surfaceHover: "#ececf1",
  text: "#0f0f0f",
  textMuted: "#6e6e80",
  textSubtle: "#9b9ba8",
  border: "#e5e5e5",
  borderStrong: "#d0d0d5",
  primary: "#0f0f0f",
  primaryHover: "#2a2a2a",
  primarySoft: "#ececf1",
  primarySoftHover: "#dedee3",
  primaryText: "#ffffff",
  accentText: "#10a37f",
  focusRing: "#10a37f",
  hero: "#0f0f0f",
  heroText: "#ffffff",
},
{
  id: "openai-chatgpt-dark",
  name: "ChatGPT Dark",
  background: "#171717",
  surface: "#212121",
  surfaceMuted: "#2f2f2f",
  surfaceHover: "#383838",
  text: "#ececec",
  textMuted: "#b4b4b4",
  textSubtle: "#8e8ea0",
  border: "#3f3f3f",
  borderStrong: "#525252",
  primary: "#ececec",
  primaryHover: "#ffffff",
  primarySoft: "#2f2f2f",
  primarySoftHover: "#383838",
  primaryText: "#171717",
  accentText: "#10a37f",
  focusRing: "#10a37f",
  hero: "#000000",
  heroText: "#ececec",
},
];

export const defaultCustomPalette = (): ThemePalette => ({
  ...builtInPalettes[0],
  id: crypto.randomUUID(),
  name: "Min palett",
});

export function normalizePalette(
  palette: Partial<ThemePalette> & Pick<ThemePalette, "id" | "name">,
): ThemePalette {
  const fallback = builtInPalettes[0];
  return {
    ...fallback,
    ...palette,
    surfaceHover:
      palette.surfaceHover ?? palette.surfaceMuted ?? fallback.surfaceHover,
    textSubtle: palette.textSubtle ?? palette.textMuted ?? fallback.textSubtle,
    borderStrong:
      palette.borderStrong ?? palette.border ?? fallback.borderStrong,
    primarySoftHover:
      palette.primarySoftHover ??
      palette.primarySoft ??
      fallback.primarySoftHover,
    accentText: palette.accentText ?? palette.primary ?? fallback.accentText,
    focusRing: palette.focusRing ?? palette.primarySoft ?? fallback.focusRing,
  };
}

export function resolvePalette(
  selectedId: string,
  customPalettes: ThemePalette[],
) {
  return normalizePalette(
    customPalettes.find((palette) => palette.id === selectedId) ??
      builtInPalettes.find((palette) => palette.id === selectedId) ??
      builtInPalettes[0],
  );
}

export function isDarkPalette(palette: ThemePalette) {
  const hex = palette.background.replace("#", "");
  const [r, g, b] = [0, 2, 4].map((index) =>
    Number.parseInt(hex.slice(index, index + 2), 16),
  );
  return (r * 299 + g * 587 + b * 114) / 1000 < 128;
}

export function applyPalette(palette: ThemePalette) {
  const root = document.documentElement;
  root.dataset.palette = palette.id;
  root.dataset.paletteTone = isDarkPalette(palette) ? "dark" : "light";
  const values: Record<string, string> = {
    "--palette-background": palette.background,
    "--palette-surface": palette.surface,
    "--palette-surface-muted": palette.surfaceMuted,
    "--palette-surface-hover": palette.surfaceHover,
    "--palette-text": palette.text,
    "--palette-text-muted": palette.textMuted,
    "--palette-text-subtle": palette.textSubtle,
    "--palette-border": palette.border,
    "--palette-border-strong": palette.borderStrong,
    "--palette-primary": palette.primary,
    "--palette-primary-hover": palette.primaryHover,
    "--palette-primary-soft": palette.primarySoft,
    "--palette-primary-soft-hover": palette.primarySoftHover,
    "--palette-primary-text": palette.primaryText,
    "--palette-accent-text": palette.accentText,
    "--palette-focus-ring": palette.focusRing,
    "--palette-hero": palette.hero,
    "--palette-hero-text": palette.heroText,
    // shadcn/ui tokens. Keeping these in sync lets official shadcn components
    // participate in Lectio's selectable palettes instead of being stuck on
    // the scaffold's default Zinc colors.
    "--background": palette.background,
    "--foreground": palette.text,
    "--card": palette.surface,
    "--card-foreground": palette.text,
    "--popover": palette.surface,
    "--popover-foreground": palette.text,
    "--primary": palette.primary,
    "--primary-foreground": palette.primaryText,
    "--secondary": palette.surfaceMuted,
    "--secondary-foreground": palette.text,
    "--muted": palette.surfaceMuted,
    "--muted-foreground": palette.textMuted,
    "--accent": palette.surfaceHover,
    "--accent-foreground": palette.text,
    "--border": palette.border,
    "--input": palette.borderStrong,
    "--ring": palette.focusRing,
    "--sidebar": palette.surface,
    "--sidebar-foreground": palette.text,
    "--sidebar-primary": palette.primary,
    "--sidebar-primary-foreground": palette.primaryText,
    "--sidebar-accent": palette.surfaceHover,
    "--sidebar-accent-foreground": palette.text,
    "--sidebar-border": palette.border,
    "--sidebar-ring": palette.focusRing,
  };
  Object.entries(values).forEach(([name, value]) =>
    root.style.setProperty(name, value),
  );
}
